### ISSUE TITLE
Labels Misaligned

### ISSUE THREAD

**Issue by thedigitalman** [NewSignature/us-map#14]
I'm using the example from the demo (http://newsignature.github.com/us-map/#demo), but the labels are misaligned.

Is there any way to readjust their position?

![ss-us-map-labels-misaligned](https://f.cloud.github.com/assets/2981750/210751/0e9b0daa-829c-11e2-937d-dde7d17378b8.png)

**Comment by rickrussie** [comment]
Did you find a fix for this thedigitalman?

**Comment by KyleWullschleger** [comment]
I'm having the same issue, was there a solution found?

**Comment by rickrussie** [comment]
We didn't find a solution, just a clue. When we insert the map after page load (e.g. in a modal popover) it misaligns the text, but when we load it on page load they are fine. We ended up loading it in an iFrame inside the popover instead. Let me know if you find another solution.

**Comment by LukeXF** [comment]
The misalignment of the labels is caused by loading in the map when map isn't visible. 

An example of this could be that you've loaded your map in a pop up, modal, carousel or simple the element just isn't visible on it's own because of your custom code.

**To fix this, rather than initialing the map on page load, initialize it when the element becomes visible.** 

Using the setTimeout() function could help with this (because all animations/fades need to be completed before loading in the map.
