### ISSUE TITLE
Fancybox Label Alignment

### ISSUE THREAD

**Issue by ghost** [NewSignature/us-map#46]
Hey All,

Awesome plugin, love this thing! Running into a unique issue when using this map selector inside of a fancybox where the labels don't line up with their backing. I've added the map to the regular page and it functions perfectly but in the fancybox there seems to be some kind of initialization issue happening, please check out the image.

If there's any chance someone can give me a hand with this today it'd be hugely appreciated. 
![usa-maps-fancybox-issue](https://cloud.githubusercontent.com/assets/4855732/5317889/21c4367c-7c69-11e4-8000-4d9d80bf9af7.png)

**Comment by jackvial** [comment]
+1

**Comment by LukeXF** [comment]
I have this problem as well, I think it could be due to bootstrap or that the labels cannot be placed properly when then map is hidden.

**Comment by LukeXF** [comment]
+1 would like to see this issue resolved.

**Comment by LukeXF** [comment]
Okay did some research:

The misalignment of the labels is caused by loading in the map when map isn't visible. 

An example of this could be that you've loaded your map in a pop up, modal, carousel or simple the element just isn't visible on it's own because of your custom code.

**To fix this, rather than initialing the map on page load, initialize it when the element becomes visible.** 

Using the setTimeout() function could help with this (because all animations/fades need to be completed before loading in the map.
